source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"

gem "rake", "~> 13.0.3"
gem "nokogiri", ">= 1.12.5"
gem "addressable", ">= 2.8.0"
gem "jasper"
gem "github-pages", "~> 214", group: :jekyll_plugins

